apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      env: testing
  template:
    metadata:
      name: myweb-pod
      labels:
        env: testing
        app: html-pod
    spec:
      containers:
      - name: html-pod
        image: vimal13/apache-webserver-php