apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  labels:
    env: myvolume

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
